spring:
  application:
    name: insurance-tax-api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true # TODO Config should be false to production enviroiment

jpa:
  database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /insurance/tax/v1/



